server:
  port: 8200

eureka:
  instance:
    hostname: eureka8200
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8100:8100, http://eureka8200:8200, http://eureka8300:8300
#      defaultZone: http://localhost:8100/eureka, http://localhost:8200/eureka, http://localhost:8300/eureka

spring:
  application:
    name: eureka-server