eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: consumer-depart-01-8080

spring:
  application:
    name: consumer-depart

info:
  app.version: 1.0
  app.auth: lcl
  app.name: consumer-depart