server:
  port: 9999

spring:
  cloud:
    config:
      server:
        git:
          # 设置git仓库地址
          uri: git@github.com:menglongdeye/lcl-springcloud.git
          search-paths: zzz-configfile
          # git连接超时时间
          timeout: 5
          # git分支
          default-label: main